name: streaming_platform
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  file_picker: ^5.2.2
  video_player: ^2.9.5
  http: ^1.1.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.1.5
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.1
  video_player_web: ^2.3.5
  fl_chart: ^0.65.0
  webview_flutter: ^4.0.7
  flutter_secure_storage: ^9.0.0
  share_plus: ^7.2.1
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  feexpay_flutter: ^1.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
